In [1]:
import pandas as pd

In [3]:
data = "datos_nomivac_covid19.csv"

In [5]:
# Leemos Dataframe
df = pd.read_csv(data, dtype= {'jurisdiccion_residencia_id' : object, 
                                                      'depto_residencia_id'        : object, 
                                                      'jurisdiccion_aplicacion_id' : object, 
                                                      'depto_aplicacion_id'        : object})

In [6]:
df.head()

,sexo,grupo_etario,jurisdiccion_residencia,jurisdiccion_residencia_id,depto_residencia,depto_residencia_id,jurisdiccion_aplicacion,jurisdiccion_aplicacion_id,depto_aplicacion,depto_aplicacion_id,fecha_aplicacion,vacuna,condicion_aplicacion,orden_dosis,lote_vacuna
0,F,40-49,Mendoza,50,La Paz,042,Mendoza,50,La Paz,042,2021-08-19,AstraZeneca,18 a 59 años CON Factores de Riesgo,2,NJ0037
1,F,40-49,Mendoza,50,La Paz,042,Mendoza,50,La Paz,042,2021-06-23,AstraZeneca,18 a 59 años CON Factores de Riesgo,1,NH0163
2,M,40-49,Buenos Aires,06,Quilmes,658,Buenos Aires,06,Quilmes,658,2021-06-08,AstraZeneca,Salud,1,ABX8674
3,M,40-49,Buenos Aires,06,Quilmes,658,Buenos Aires,06,Quilmes,658,2021-09-16,AstraZeneca,Estratégico,2,NK0224
4,M,40-49,Buenos Aires,06,San Isidro,756,CABA,02,COMUNA 4,004,2021-06-24,AstraZeneca,18 a 59 años CON Factores de Riesgo,1,NH0163

In [8]:
# Filtramos Vacunados por cada dosis
df_1dosis = df[(df.orden_dosis == 1)]
df_2dosis = df[(df.orden_dosis == 2)]

In [9]:
df_1dosis.head()

,sexo,grupo_etario,jurisdiccion_residencia,jurisdiccion_residencia_id,depto_residencia,depto_residencia_id,jurisdiccion_aplicacion,jurisdiccion_aplicacion_id,depto_aplicacion,depto_aplicacion_id,fecha_aplicacion,vacuna,condicion_aplicacion,orden_dosis,lote_vacuna
1,F,40-49,Mendoza,50,La Paz,042,Mendoza,50,La Paz,042,2021-06-23,AstraZeneca,18 a 59 años CON Factores de Riesgo,1,NH0163
2,M,40-49,Buenos Aires,06,Quilmes,658,Buenos Aires,06,Quilmes,658,2021-06-08,AstraZeneca,Salud,1,ABX8674
4,M,40-49,Buenos Aires,06,San Isidro,756,CABA,02,COMUNA 4,004,2021-06-24,AstraZeneca,18 a 59 años CON Factores de Riesgo,1,NH0163
6,F,60-69,Buenos Aires,06,La Matanza,427,Buenos Aires,06,La Matanza,427,2021-05-05,Sputnik,60 o más años,1,I-450321
8,F,60-69,Buenos Aires,06,La Plata,441,Buenos Aires,06,La Plata,441,2021-04-23,AstraZeneca,Salud,1,CTMAV534

In [10]:
df_2dosis.head()

,sexo,grupo_etario,jurisdiccion_residencia,jurisdiccion_residencia_id,depto_residencia,depto_residencia_id,jurisdiccion_aplicacion,jurisdiccion_aplicacion_id,depto_aplicacion,depto_aplicacion_id,fecha_aplicacion,vacuna,condicion_aplicacion,orden_dosis,lote_vacuna
0,F,40-49,Mendoza,50,La Paz,042,Mendoza,50,La Paz,042,2021-08-19,AstraZeneca,18 a 59 años CON Factores de Riesgo,2,NJ0037
3,M,40-49,Buenos Aires,06,Quilmes,658,Buenos Aires,06,Quilmes,658,2021-09-16,AstraZeneca,Estratégico,2,NK0224
5,M,40-49,Buenos Aires,06,San Isidro,756,CABA,02,COMUNA 4,004,2021-09-26,AstraZeneca,40 a 49 años SIN Factores de Riesgo,2,ABZ3413
7,F,60-69,Buenos Aires,06,La Matanza,427,Buenos Aires,06,La Matanza,427,2021-09-09,Sputnik,60 o más años,2,LZS3LZS4
9,F,60-69,Buenos Aires,06,La Plata,441,Buenos Aires,06,La Plata,441,2021-07-07,AstraZeneca,60 o más años,2,NH0335

In [11]:
# Agrupamos por dosis y jurisdiccion
df_agrupado_1dosis = df_1dosis.groupby(['jurisdiccion_aplicacion']).size().reset_index(name='counts')
df_agrupado_2dosis = df_2dosis.groupby(['jurisdiccion_aplicacion']).size().reset_index(name='counts')

In [12]:
df_agrupado_2dosis

   jurisdiccion_aplicacion   counts
0             Buenos Aires  8526738
1                     CABA  1932384
2                Catamarca   192125
3                    Chaco   455740
4                   Chubut   261844
5               Corrientes   437715
6                  Córdoba  1966090
7               Entre Ríos   614775
8                  Formosa   288949
9                    Jujuy   320560
10                La Pampa   215252
11                La Rioja   204997
12                 Mendoza   934349
13                Misiones   428564
14                 Neuquén   331529
15               Río Negro   389781
16                   Salta   519903
17                San Juan   386543
18                San Luis   289840
19              Santa Cruz   153091
20                Santa Fe  1869446
21     Santiago del Estero   519695
22        Tierra del Fuego    94051
23                 Tucumán   748773

In [13]:
df_agrupado_1dosis

   jurisdiccion_aplicacion    counts
0             Buenos Aires  11440555
1                     CABA   2319981
2                Catamarca    298873
3                    Chaco    713721
4                   Chubut    376931
5               Corrientes    713110
6                  Córdoba   2504253
7               Entre Ríos    880251
8                  Formosa    431374
9                    Jujuy    509423
10                La Pampa    251173
11                La Rioja    269541
12                 Mendoza   1239099
13                Misiones    662432
14                 Neuquén    454432
15               Río Negro    508106
16                   Salta    818098
17                San Juan    507282
18                San Luis    347288
19              Santa Cruz    212127
20                Santa Fe   2403129
21     Santiago del Estero    670918
22        Tierra del Fuego    116131
23                 Tucumán   1042325

In [15]:
# Cantidad de Habitantes por jurisdiccion
# Fuente: 
poblacion = {
    "Buenos Aires": 17709598,
    "CABA": 3078836,
    "Catamarca": 418991,
    "Chaco": 1216247,
    "Chubut": 629181,
    "Corrientes": 1130320,
    "Córdoba": 3798261,
    "Entre Ríos": 1398510,
    "Formosa": 610019,
    "Jujuy": 779212,
    "La Pampa": 361394,
    "La Rioja": 398648,
    "Mendoza": 2010363,
    "Misiones": 1274992,
    "Neuquén": 672461,
    "Río Negro": 757052,
    "Salta": 1441988,
    "San Juan": 789489,
    "San Luis": 514610,
    "Santa Cruz": 374756,
    "Santa Fe": 3563390,
    "Santiago del Estero": 988245,
    "Tierra del Fuego": 177697,
    "Tucumán": 1714487
}

poblacion_df = pd.DataFrame(poblacion.items(), columns=['jurisdiccion', 'habitantes'])
poblacion_df

           jurisdiccion  habitantes
0          Buenos Aires    17709598
1                  CABA     3078836
2             Catamarca      418991
3                 Chaco     1216247
4                Chubut      629181
5            Corrientes     1130320
6               Córdoba     3798261
7            Entre Ríos     1398510
8               Formosa      610019
9                 Jujuy      779212
10             La Pampa      361394
11             La Rioja      398648
12              Mendoza     2010363
13             Misiones     1274992
14              Neuquén      672461
15            Río Negro      757052
16                Salta     1441988
17             San Juan      789489
18             San Luis      514610
19           Santa Cruz      374756
20             Santa Fe     3563390
21  Santiago del Estero      988245
22     Tierra del Fuego      177697
23              Tucumán     1714487

In [20]:
# Unimos 
densidad_1dosis = pd.merge(df_agrupado_1dosis, poblacion_df, how='left', left_on=['jurisdiccion_aplicacion'], right_on=['jurisdiccion'])
densidad_1dosis["porcentaje_vacunados"] = densidad_1dosis.counts * 100 / densidad_1dosis.habitantes
densidad_1dosis = densidad_1dosis.drop(columns=['counts', 'jurisdiccion_aplicacion', 'habitantes'])
densidad_1dosis

           jurisdiccion  porcentaje_vacunados
0          Buenos Aires             64.600873
1                  CABA             75.352536
2             Catamarca             71.331604
3                 Chaco             58.682241
4                Chubut             59.908198
5            Corrientes             63.089214
6               Córdoba             65.931567
7            Entre Ríos             62.942060
8               Formosa             70.714847
9                 Jujuy             65.376688
10             La Pampa             69.501154
11             La Rioja             67.613785
12              Mendoza             61.635585
13             Misiones             51.955777
14              Neuquén             67.577451
15            Río Negro             67.116394
16                Salta             56.734037
17             San Juan             64.254473
18             San Luis             67.485669
19           Santa Cruz             56.604030
20             Santa Fe             67.439405
21  Santiago del Estero             67.889845
22     Tierra del Fuego             65.353382
23              Tucumán             60.795153

In [21]:
# Unimos 
densidad_2dosis = pd.merge(df_agrupado_2dosis, poblacion_df, how='left', left_on=['jurisdiccion_aplicacion'], right_on=['jurisdiccion'])
densidad_2dosis["porcentaje_vacunados"] = densidad_2dosis.counts * 100 / densidad_2dosis.habitantes
densidad_2dosis = densidad_2dosis.drop(columns=['counts', 'jurisdiccion_aplicacion', 'habitantes'])
densidad_2dosis

           jurisdiccion  porcentaje_vacunados
0          Buenos Aires             48.147553
1                  CABA             62.763460
2             Catamarca             45.854207
3                 Chaco             37.471007
4                Chubut             41.616641
5            Corrientes             38.724874
6               Córdoba             51.762899
7            Entre Ríos             43.959285
8               Formosa             47.367213
9                 Jujuy             41.138997
10             La Pampa             59.561587
11             La Rioja             51.423060
12              Mendoza             46.476631
13             Misiones             33.613074
14              Neuquén             49.300852
15            Río Negro             51.486688
16                Salta             36.054600
17             San Juan             48.961163
18             San Luis             56.322263
19           Santa Cruz             40.850847
20             Santa Fe             52.462571
21  Santiago del Estero             52.587668
22     Tierra del Fuego             52.927737
23              Tucumán             43.673297

In [22]:
# Exportamos json
densidad_1dosis.to_json('densidad1dosis.json', orient = 'records')
densidad_2dosis.to_json('densidad2dosis.json', orient = 'records')